### ISSUE TITLE
Absence or presences of @JsonCreator doesn't really matter...

### ISSUE THREAD

**Issue by apatrida** [FasterXML/jackson-module-paranamer#11]
If you commit @JsonCreator then this code still works.  Jackson doesn't really seem to check it for the "success" cases.

In the unit test where it should fail without the paranamer module, it fails with a different exception message when @JsonCreator isn't present.  Instead of "has no property name annotation" it is "no suitable constructor" which is as expected.  But add the Paramer module and absence of @JsonCreator doesn't change anything, the classes are still constructible.  

Is that intended?

**Comment by jkubrynski** [comment]
The question is if it's a bug or it's a feature? In my opinion it's really cool, that I don't have to add @JsonCreator, because it let me to keep my pojos clear. Maybe you'll consider allowing such behaviour? It could be controlled by some parameter to content everyone :)

**Comment by cowtowncoder** [comment]
I have forgotten what exactly the original case was. Behavior with Jackson 2.4 is what it is, that is, can not be changed due to multiple underlying issues (regarding implicit vs explicit names).

But in 2.5, things should work so that:

1. As long as _every_ argument has an explicit `@JsonProperty` annotation, `@JsonCreator` is not needed.
2. Further, single-parameter creators may be discovered without `@JsonCreator`, as long as type is one of small number of well-known native types (String, Long/long, Integer/int, Boolean/boolean)

other than this, modules may choose to report explicit names (similar to having `@JsonProperty`). If so, it may be possible to omit `@JsonCreator`. Modules should NOT indicate that default name that construct argument has is explicit for basic Java usage (Scala module, on the other hand, may do that, because Scala language rules enforce single constructor definition).

Not sure if above answers the question here, but that is the ruleset as of 2.5.0.

**Comment by lpandzic** [comment]
> The question is if it's a bug or it's a feature? In my opinion it's really cool, that I don't have to add @JsonCreator, because it let me to keep my pojos clear. Maybe you'll consider allowing such behaviour? It could be controlled by some parameter to content everyone :)

The change originated from the jackson-parameter-module-names and this was one of the original features for that module but we are not there yet, see [this issue](https://github.com/FasterXML/jackson-module-parameter-names/issues/13) for more details.

**Comment by jaysonminard** [comment]
@cowtowncoder one problem with "modules may choose to report explicit names (similar to having @JsonProperty)" is that explicit names have different behaviour, such as not being converted to camel or pascal casing.  I tried using this before and it broke the ability to configure the casing behaviour.  What I wanted was to say "I know the parameter name, but treat it as normal" and that isn't allowed.

**Comment by cowtowncoder** [comment]
@jaysonminard Right, non-empty explicit name is taken as is. Returning "" used to indicate "use implicit name, but consider this property to be known to exist regardless of visibility".

However, with 2.4 and above, there is a way to offer implicit name that is still subject to name mangling with:

```java
public class AnnotationIntrospector {
    public String findImplicitPropertyName(AnnotatedMember member) {  }
}
```

so this is what you want to use to provide, for example, parameter names for creators.
